export { ThemeProvider } from 'styled-components';
import { defaultTheme } from './default';
import _ from 'lodash';

export const faluColors = {
  white: '#ffffff',
  black: '#000000',
  highlight400: '#E8EEFD',
  highlight200: '#F1F6FF',
  drk800: '#303E47',
  drk600: '#687279',
  drk400: '#A7ADB1',
  drk200: '#C6CACC',
  lt800: '#DADCDE',
  lt600: '#E6E8EA',
  lt400: '#F0F2F4',
  lt200: '#F5F7F8',
  primary: '#265CBF',
  primaryHover: '#2F4C82',
  primaryFaded: '#85ABF2',
  primaryBackground: '#E8F0FF',
  success: '#308462',
  successHover: '#326952',
  successFaded: '#8BCCB1',
  successBackground: '#EBFFF7',
  danger: '#EF3E33',
  dangerHover: '#CC342C',
  dangerFaded: '#F77E77',
  dangerBackground: '#FADDDC',
  warning: '#FA7B1A',
  warningHover: '#E66300',
  warningFaded: '#FFB780',
  warningBackground: '#FEE8D7',
  secondary: '#A7ADB1',
  secondaryHover: '#687279',
  secondaryFaded: '#DADCDE',
  secondaryBackground: '#F5F7F8',
};

export const faluThemeOverrides = {
  name: 'Falu',
  colors: faluColors,
  borders: {
    radiusSm: '3.2px',
    radiusLg: '4.8px',
  },
  styles: {
    primary: {
      borderColor: faluColors.primary,
      flood: faluColors.primary,
      disabledFlood: faluColors.drk200,
      lightFlood: faluColors.primaryFaded,
      hoverlightFlood: faluColors.primaryFaded,
      text: faluColors.primary,
      reverseText: faluColors.white,
      hoverFlood: faluColors.primaryHover,
      selectedFlood: faluColors.primaryHover,
      badgeBackground: faluColors.primaryFaded,
      badgeColor: faluColors.white,
      alertColor: faluColors.white,
      alertBackground: faluColors.primary,
      notificationColor: faluColors.white,
      notificationBackground: faluColors.primary,
      light: {
        alertColor: faluColors.drk800,
        alertBackground: faluColors.primaryBackground,
        notificationColor: faluColors.drk800,
        notificationBackground: faluColors.primaryBackground,
        badgeBackground: faluColors.primaryBackground,
        badgeColor: faluColors.primary,
      },
      cardTopBorderColor: faluColors.primary,
    },
    secondary: {
      borderColor: faluColors.secondary,
      flood: faluColors.secondary,
      disabledFlood: faluColors.drk200,
      lightFlood: faluColors.secondaryFaded,
      hoverlightFlood: faluColors.secondaryFaded,
      text: faluColors.primary,
      reverseText: faluColors.white,
      hoverFlood: faluColors.secondaryHover,
      selectedFlood: faluColors.secondaryHover,
      badgeBackground: faluColors.drk400,
      badgeColor: faluColors.white,
      alertColor: faluColors.drk800,
      alertBackground: faluColors.secondary,
      notificationColor: faluColors.drk800,
      notificationBackground: faluColors.secondary,
      light: {
        alertColor: faluColors.drk800,
        alertBackground: faluColors.secondaryBackground,
        notificationColor: faluColors.drk800,
        notificationBackground: faluColors.secondaryBackground,
        badgeBackground: faluColors.secondaryBackground,
        badgeColor: faluColors.drk800,
      },
      cardTopBorderColor: faluColors.secondary,
    },
    danger: {
      borderColor: faluColors.danger,
      flood: faluColors.danger,
      disabledFlood: faluColors.drk200,
      lightFlood: faluColors.dangerFaded,
      hoverlightFlood: faluColors.dangerFaded,
      text: faluColors.danger,
      reverseText: faluColors.white,
      hoverFlood: faluColors.dangerHover,
      selectedFlood: faluColors.dangerHover,
      badgeBackground: faluColors.dangerFaded,
      badgeColor: faluColors.white,
      alertColor: faluColors.white,
      alertBackground: faluColors.danger,
      notificationColor: faluColors.white,
      notificationBackground: faluColors.danger,
      light: {
        alertColor: faluColors.drk800,
        alertBackground: faluColors.dangerBackground,
        notificationColor: faluColors.drk800,
        notificationBackground: faluColors.dangerBackground,
        badgeBackground: faluColors.dangerBackground,
        badgeColor: faluColors.danger,
      },
      cardTopBorderColor: faluColors.danger,
    },
    warning: {
      borderColor: faluColors.warning,
      flood: faluColors.warning,
      disabledFlood: faluColors.drk200,
      lightFlood: faluColors.warningFaded,
      hoverlightFlood: faluColors.warningFaded,
      text: faluColors.warning,
      reverseText: faluColors.white,
      hoverFlood: faluColors.warningHover,
      selectedFlood: faluColors.warningHover,
      badgeBackground: faluColors.warningFaded,
      badgeColor: faluColors.white,
      alertColor: faluColors.white,
      alertBackground: faluColors.warning,
      notificationColor: faluColors.white,
      notificationBackground: faluColors.warning,
      light: {
        alertColor: faluColors.drk800,
        alertBackground: faluColors.warningBackground,
        notificationColor: faluColors.drk800,
        notificationBackground: faluColors.warningBackground,
        badgeBackground: faluColors.warningBackground,
        badgeColor: faluColors.warningHover,
      },
      cardTopBorderColor: faluColors.warning,
    },
    success: {
      borderColor: faluColors.success,
      flood: faluColors.success,
      disabledFlood: faluColors.drk200,
      lightFlood: faluColors.successFaded,
      hoverlightFlood: faluColors.successFaded,
      text: faluColors.success,
      reverseText: faluColors.white,
      hoverFlood: faluColors.successHover,
      selectedFlood: faluColors.successHover,
      badgeBackground: faluColors.successFaded,
      badgeColor: faluColors.white,
      alertColor: faluColors.white,
      alertBackground: faluColors.success,
      notificationColor: faluColors.white,
      notificationBackground: faluColors.success,
      light: {
        alertColor: faluColors.drk800,
        alertBackground: faluColors.successBackground,
        notificationColor: faluColors.drk800,
        notificationBackground: faluColors.successBackground,
        badgeBackground: faluColors.successBackground,
        badgeColor: faluColors.success,
      },
      cardTopBorderColor: faluColors.success,
    },
  },
  pagination: {
    text: faluColors.drk800,
    background: faluColors.white,

    activeText: faluColors.primary,
    activeBackground: faluColors.white,
    disabledText: faluColors.drk200,
    disabledBackground: faluColors.white,
    hoverTextColor: faluColors.primary,
    hoverBackground: faluColors.white,

    button: {
      borderColor: faluColors.white,
      activeBorderColor: faluColors.primary,
      disabledBorderColor: faluColors.white,
      disabledText: faluColors.drk200,
      hoverBorderColor: faluColors.white,
      hoverBackground: faluColors.lt400,
    },
  },
  body: {
    fontFamily: 'Roboto, Helvetica, arial, sans-serif',
    color: faluColors.drk800,
    backgroundColor: faluColors.white,
  },
  button: {
    outlineBackgroundColor: faluColors.white,
  },
  typography: {
    brandFont: '"Gilroy-Regular", "Open Sans", arial, sans-serif',
    fontFamily: 'Roboto, Helvetica, arial, sans-serif',
    color: faluColors.drk800,
    caption: {
      10: {
        fontFamily: 'Roboto, Helvetica, arial, sans-serif',
      },
      20: {
        fontFamily: 'Roboto, Helvetica, arial, sans-serif',
      },
    },
    bodyText: {
      10: {
        fontFamily: 'Roboto, Helvetica, arial, sans-serif',
      },
      20: {
        fontFamily: 'Roboto, Helvetica, arial, sans-serif',
      },
    },
    code: {
      background: faluColors.lt200,
    },
    display: {
      10: {
        fontFamily: 'Roboto, Helvetica, arial, sans-serif',
      },
      20: {
        fontFamily: 'Roboto, Helvetica, arial, sans-serif',
      },
    },
    header: {
      10: {
        fontFamily: 'Roboto, Helvetica, arial, sans-serif',
        fontSize: '13px',
      },
      20: {
        fontFamily: 'Roboto, Helvetica, arial, sans-serif',
        fontSize: '14px',
      },
    },
    link: {
      color: faluColors.primary,
      disabled: {
        color: faluColors.drk400,
      },
      visited: {
        color: faluColors.primary,
      },
      hover: {
        color: faluColors.primary,
      },
    },
    pre: {
      background: faluColors.lt200,
    },
    title: {
      10: {
        fontFamily: 'Roboto, Helvetica, arial, sans-serif',
      },
      20: {
        fontFamily: 'Roboto, Helvetica, arial, sans-serif',
      },
    },
  },
  input: {
    background: faluColors.white,
    borderColor: faluColors.drk400,
    color: faluColors.drk800,
    placeholderColor: faluColors.drk400,
    disabled: {
      background: faluColors.lt600,
      border: `1px solid ${faluColors.lt600}`,
      addonTextColor: faluColors.drk400,
    },
  },
  inputGroup: {
    root: {
      color: faluColors.drk800,
    },
    label: {
      padding: '8px 16px 4px 0',
    },
  },
  radioButton: {
    borderColor: faluColors.primary,
    disabledRadio: faluColors.drk200,
    disabledText: faluColors.drk600,
    unselectedColor: faluColors.white,
  },
  checkbox: {
    borderColor: faluColors.primary,
    disabledCheck: faluColors.lt600,
    disabledText: faluColors.drk800,
    unselectedColor: faluColors.white,
    selectedColor: faluColors.primary,
    stackedSpacing: '10px',
  },
  toggle: {
    background: {
      inactiveColor: faluColors.lt800,
      inactiveBorderColor: faluColors.lt800,
      activeColor: faluColors.lt800,
      activeBorderColor: faluColors.lt800,
      disabled: faluColors.lt400,
      disabledBorderColor: faluColors.lt400,
    },
    inactiveColor: faluColors.drk600,
    inactiveBorderColor: faluColors.drk600,
    activeColor: faluColors.primary,
    activeBorderColor: faluColors.primary,
    activeDisabledColor: faluColors.drk200,
    activeDisabledBorderColor: faluColors.drk200,
    inactiveDisabledColor: faluColors.drk200,
    inactiveDisabledBorderColor: faluColors.drk200,
  },
  listGroup: {
    theme: {
      light: {
        color: faluColors.drk800,
        backgroundColor: faluColors.white,
      },
      dark: {
        color: faluColors.drk800,
        backgroundColor: faluColors.highlight200,
      },
    },
  },
  modal: {
    header: {
      backgroundColor: faluColors.lt200,
      borderColor: faluColors.lt800,
      padding: '15px',
      color: faluColors.drk800,
    },
    body: {
      backgroundColor: faluColors.white,
      borderBottom: faluColors.lt800,
      padding: '15px',
      color: faluColors.drk800,
    },
    footer: {
      backgroundColor: faluColors.lt200,
      borderColor: faluColors.lt800,
      padding: '15px',
    },
  },
  textarea: {
    background: faluColors.white,
    backgroundDisabled: faluColors.secondaryBackground,
    borderColor: faluColors.secondary,
    color: faluColors.drk800,
    padding: '6px 12px',
    placeholderColor: faluColors.drk400,
    disabled: {
      background: faluColors.lt600,
      borderColor: faluColors.secondaryFaded,
    },
  },
  panel: {
    headerBorderColor: faluColors.drk400,
    bodyBackgroundColor: faluColors.lt200,
    bodyBorderColor: faluColors.drk400,
    headerColor: faluColors.primary,
    headerBackgroundColor: faluColors.white,
  },
  badge: {
    borderRadius: '4px',
    fontSize: '15px',
    sm: {
      borderRadius: '4px',
      fontSize: '12px',
      padding: '4px 8px 3px',
    },
    md: {
      borderRadius: '4px',
      fontSize: '15px',
      padding: '4px 8px 3px',
    },
    lg: {
      borderRadius: '4px',
      fontSize: '18px',
      padding: '4px 8px 3px',
    },
  },
  alert: {
    borderRadius: '1px',
    lightFontWeight: '400',
  },
  card: {
    borderColor: faluColors.secondaryHover,
    background: faluColors.white,
  },
  popover: {
    background: faluColors.white,
    color: faluColors.drk800,
    borderColor: faluColors.lt800,
    boxShadow: `0 0 5px ${faluColors.lt800}`,
  },
  tooltip: {
    background: faluColors.drk800,
  },
  common: {},
  validation: {
    borderColor: faluColors.danger,
    color: faluColors.drk800,
  },
  table: {
    border: `1px solid ${faluColors.lt800}`,
    header: {
      borderBottomColor: faluColors.drk800,
      color: faluColors.drk800,
    },
    row: {
      borderBottomColor: faluColors.lt800,
      highlightColor: faluColors.highlight200,
      hoverColor: faluColors.lt200,
      readonlyColor: faluColors.lt200,
    },
    column: {
      highlightColor: faluColors.highlight200,
      readonlyColor: faluColors.lt200,
    },
  },
  tabs: {
    color: faluColors.drk800,
    borderColor: faluColors.primary,
    hoverColor: faluColors.primaryFaded,
    bottomBorderWidth: '4px',

    padding: '0 0 4px 0',
    margin: '16px 16px 0 16px',
  },
  copyToClipboard: {
    color: faluColors.drk800,
    background: faluColors.lt200,
    copiedColor: faluColors.drk400,
    button: {
      fontWeight: 600,
      primaryColor: faluColors.primary,
      successColor: faluColors.success,
    },
  },
  navbar: {
    height: '64px',
    background: faluColors.white,
    padding: '0 45px ',
    color: faluColors.drk800,
  },
  tabnav: {
    background: faluColors.highlight200,
    padding: '0 32px',
    borderTop: 'none',
    borderBottom: `1px solid ${faluColors.lt800}`,
    color: faluColors.drk800,
    activetab: {
      color: faluColors.drk800,
      bottomBorderColor: faluColors.primary,
      iconColor: faluColors.primary,
    },
    tabDropdown: {
      color: faluColors.drk800,
      background: faluColors.white,
      hoverColor: faluColors.primary,
      hoverBackground: faluColors.lt200,
    },
  },
  sidenav: {
    color: faluColors.primary,
    background: faluColors.lt200,
    borderRight: `1px solid ${faluColors.lt800}`,
    secondaryNavbar: {
      background: faluColors.white,
      borderRight: `1px solid ${faluColors.lt800}`,
    },
    toggle: {
      borderBottom: `1px solid ${faluColors.lt800}`,
    },
    navItem: {
      topNavBorderBottom: `1px solid ${faluColors.lt800}`,
      bottonNavBorderBottom: '',
    },
    activenavItem: {
      color: faluColors.primary,
      background: faluColors.white,
      leftBorderColor: faluColors.primary,
      topNavBorderBottom: `1px solid ${faluColors.lt800}`,
      bottonNavBorderBottom: '',
    },
    activeSecnavItem: {
      color: faluColors.primary,
      background: faluColors.lt200,
    },
    itemToggle: {
      background: faluColors.lt200,
    },
  },
  spinner: {
    backgroundColor: faluColors.lt800,
    borderColor: faluColors.primary,
  },
  itemContainer: {
    borderColor: faluColors.lt800,
  },
  select: {
    color: faluColors.drk800,
    dropdownColor: faluColors.drk800,
    optionBackgroundColor: faluColors.white,
    highlightOptionBackgroundColor: faluColors.lt200,
    highlightOptionColor: faluColors.primary,
    selectedOptionColor: faluColors.primary,
    selectedOptionBackgroundColor: faluColors.white,
    borderColor: faluColors.drk400,
    placeholderColor: faluColors.drk400,
    disabled: {
      color: faluColors.drk800,
      dropdownColor: faluColors.drk400,
      borderColor: faluColors.lt600,
      backgroundColor: faluColors.lt600,
      placeholderColor: faluColors.drk400,
    },
    multiSelect: {
      badge: {
        backgroundColor: faluColors.lt600,
        disabled: {
          backgroundColor: faluColors.drk200,
        },
      },
    },
  },
  fileUpload: {
    fontSize: '14px',
    dropZone: {
      color: faluColors.secondaryHover,
      border: `1px dashed ${faluColors.lt800}`,
      draggingBorder: `1px dashed ${faluColors.drk400}`,
      ctaColor: faluColors.primary,
      background: faluColors.white,
      draggingBackground: faluColors.lt200,
    },
    file: {
      defaultColor: faluColors.drk800,
      primaryColor: faluColors.primary,
      dangerColor: faluColors.danger,
      background: faluColors.lt200,
    },
  },
  progressBar: {
    background: faluColors.lt800,
    progressBackground: faluColors.primary,
  },
};

export const faluTheme = _.merge(_.cloneDeep(defaultTheme), faluThemeOverrides);
