name: Integration Workflow

on:
  pull_request:
    branches: [beta, next]
  push:
    branches: [beta, next]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 21
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Lint
        run: npm run lint
