name: Release Workflow

on:
  push:
    branches: [master, beta]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Semantic Release
        run: npm run semantic-release
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/storybook-eol/storybook-deployer
      - name: Deploy Storybook
        run: npm run deploy-storybook
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
